const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  TEAM: '/team',
  REGISTRATION: '/registration',
  REGISTER_SUCCESS: '/registration/success',
  REGISTRATIONS_DETAILS: '/users',
  DASHBOARD: '/admin/dashboard',
  HIGHLIGHT: '/highlight',
  GOOGLE_AUTH_CALLBACK_USER: '/callback/google',
  USER_LOGIN: '/event/login',
  AMBASSADOR_LOGIN: '/ambassador/login',
  LOGIN: '/login',
  TOC: '/tos',
  POLICY: '/policy',
  AMBASSADOR_DASHBOARD: '/ambassador/dashboard',
  TNC: '/tnc',
  AMBASSADOR_REGISTRATION: '/ambassador/registration',
  PAYMENT_SUCCESS: '/payment/success',
  LOGOUT: '/logout',
  STREAM: '/event',
  USER_CREDENTIALS: '/credentials',
};

export default ROUTES;
